---
name: Backlog Limits Checker
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: ['master']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  check_suse_qa_tools_backlog_limits:
    # prevent running this on forks or any other branches
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'os-autoinst' || github.ref == 'refs/heads/testworkflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - uses: openSUSE/backlogger@3d037a7decf5a6baf4adb762d4bb33058c5f1ee1  # main
        with:
          redmine_api_key: ${{ secrets.REDMINE_API_KEY }}
          webhook_url: ${{ secrets.WEBHOOK_URL }}
      - uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f  # v4.8.0
        with:
          folder: gh-pages
          clean-exclude: pr-preview
